version: '3.9'

services:
  game-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: game-server
    container_name: game-server
    ports:
      - "50001:50001"
      # - "19001:19001"
    depends_on:
      - db
    networks:
      game-server-network:
        ipv4_address: 172.100.0.3
    
  db:
    image: mysql:latest
    container_name: game-server-mysql
    ports:
      - "53306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gameserver
      MYSQL_USER: lin
      MYSQL_PASSWORD: lin
    volumes:
      - ./dev/db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      game-server-network:
        ipv4_address: 172.100.0.2
    
networks:
  game-server-network:
    name: game-server-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/16