version: '3.9'

services:
  game-server:
    build: .
    container_name: game-server
    ports:
      - "10001:10001"
      - "19001:19001"
    depends_on:
      - mysql
    
  mysql:
    image: mysql:latest
    container_name: game-server-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PWD}
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db: